name: 'Verify OpenAPI Specs'

on: [push]

jobs:
  compare-openapi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install TypeSpec CLI
      run: npm install -g @typespec/compiler

    - name: Install json2yaml
      run: npm install -g json2yaml

    #- name: Install openapi-diff
    #  run: npm install -g openapi-diff

    - name: Install oasdiff
      run: curl -fsSL https://raw.githubusercontent.com/tufin/oasdiff/main/install.sh | sh

    - name: NPM install
      run: |
        cd API_Corrections/
        npm install

    - name: Build .NET project and run tests
      run: |
        cd CorrectionsApi/
        dotnet build
        cd ../tests/Test
        dotnet test

    - name: Generate TypeSpec OpenAPI spec
      run: |
        cd API_Corrections/
        tsp compile .

    - name: Move generated OpenAPI spec to standard location
      run: |
        cp API_Corrections/tsp-output/"@typespec"/openapi3/openapi.1.0.yaml openapi.yaml        

    - name: Fetch .NET OpenAPI spec
      run: |
        # Assuming dotnet test saves the spec as dotnet_openapi.json
        json2yaml tests/Test/dotnet_openapi.json > dotnet_openapi.yaml        

    #- name: Run oasdiff and save output
    #  id: run_diff
    #  run: |        
    #    oasdiff changelog dotnet_openapi.yaml openapi.yaml       

    - name: Running OpenAPI Spec diff action
      uses: oasdiff/oasdiff-action/changelog@main
      with:
        base: dotnet_openapi.yaml
        revision: openapi.yaml
        include-path-params: true
        composed: true
        output-to-file: diff.json

    - name: See Report
      run: |
        ls